### ISSUE TITLE
[WEEK1] 강의 안내 및 컴포즈 기초 

### ISSUE THREAD

**Issue by b1urrrr** [MolComposers/Mol-Lu#1]
```
1주차 학습 기간 : ~ 23.11.16. (목)
```
# TO-DO LIST
### 섹션 0 : 강의 안내
- [x] 강의 소개
- [x] 코틀린 문법
### 섹션 1 : 컴포즈 기초
- [x] Column, Row, Text
- [x] 컴포저블, 프리뷰
- [x] Box
- [x] 리스트, LazyColumn
- [x] Image, Card, State
- [ ] Scaffold, TextField, Button, 구조분해, SnackBar, 코루틴 스코프
- [ ] Navigation
- [ ] ViewModel
- [ ] State 심화
