### ISSUE TITLE
[WEEK2] 비만도 계산기 앱 클론 코딩

### ISSUE THREAD

**Issue by b1urrrr** [MolComposers/Mol-Lu#2]
```
2주차 학습 기간 : ~ 23.11.23. (목)
```
# TO-DO LIST
### 섹션 2 : 생존코딩 앱 클론 - 비만도 계산기
- [x] 비만도 계산기 01 - 첫 번째 화면 작성
- [ ] 비만도 계산기 02 - 두 번째 화면 작성
- [ ] 비만도 계산기 03 - 화면 네비게이션
- [ ] 비만도 계산기 04 - 로직 작성
